### ISSUE TITLE
Is it possible to get the original Japanese text of this book?

### ISSUE THREAD

**Issue by jeong-jimin-github** [handmade-osdev/os-in-30-days#5]

**Comment by flysand7** [comment]
I kinda lost it myself which is part of the reason why I stopped working on this project

**Comment by Prithvi-R** [comment]
if someone get this book pdf or something please share

**Comment by flysand7** [comment]
This would be considered piracy. I suggest you buy the book from appropriate sources

**Comment by jeong-jimin-github** [comment]
If you don't live in Japan, you might as well just buy it as an ebook, which is what I did.

**Comment by Prithvi-R** [comment]
> If you don't live in Japan, you might as well just buy it as an ebook, which is what I did.
can u send me a link or the source from where i can get a ebook?

**Comment by jeong-jimin-github** [comment]
> > If you don't live in Japan, you might as well just buy it as an ebook, which is what I did.
> can u send me a link or the source from where i can get a ebook?
> 

https://www.amazon.co.jp/30日でできる-OS自作入門-川合-秀実-ebook/dp/B00IR1HYI0

If you're using the Android Phone, Google Play Books is also a good alternative.
